#!/usr/bin/env python3
import sys
import os


for i in range(10):
	os.system("cat inp"+str(i)+".txt | ./../payoff_sched | cat > exp"+str(i)+".txt")

os.system("cat inpN1.txt | ./../payoff_sched | cat > expN1.txt")
os.system("cat inpN2.txt | ./../payoff_sched | cat > expN2.txt")
os.system("cat inpN10.txt | ./../payoff_sched | cat > expN10.txt")
os.system("cat inpN1000.txt | ./../payoff_sched | cat > expN1000.txt")
